name: structurizr_new

services:
  structurizr_new:
    image: structurizr/structurizr
    command: local
    container_name: structurizr_new
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/usr/local/structurizr
    networks:
      - structurizr_new_net

networks:
  structurizr_new_net:
    name: structurizr_new_net
    driver: bridge
