name: structurizr_norgesgruppen

services:
  structurizr_norgesgruppen:
    image: structurizr/structurizr
    command: local
    container_name: structurizr_norgesgruppen
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/usr/local/structurizr
    networks:
      - structurizr_norgesgruppen_net

networks:
  structurizr_norgesgruppen_net:
    name: structurizr_norgesgruppen_net
    driver: bridge
